version: '2'

services:
  app:
    image: 'tasktracker222-1.0.0'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - DATABASE_PASSWORD=bill nye the guy
      - DATABASE_URL=jdbc:postgresql://67.187.185.122:5432/postgres
      - DATABASE_USERNAME=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - DATABASE_PASSWORD=bill nye the guy
      - DATABASE_URL=jdbc:postgresql://67.187.185.122:5432/postgres
      - DATABASE_USERNAME=postgres